# Generated by Django 4.1.1 on 2022-09-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='isPrivate',
            field=models.BooleanField(default=False, verbose_name='Приватность'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='isPrivate',
            field=models.BooleanField(default=False, verbose_name='Приватность'),
        ),
    ]
